apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-sc
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
