
apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
  namespace: storage-demo
spec:
  volumes:
    - name: shared-data
      emptyDir: {}   # общий том внутри Pod
  containers:
    - name: writer
      image: busybox:1.36
      command: ["sh","-c"]
      args:
        - |
          mkdir -p /shared
          i=0
          while true; do
            i=$((i+1))
            echo "$(date -Iseconds) line=$i" | tee -a /shared/out.txt
            sleep 5
          done
      volumeMounts:
        - name: shared-data
          mountPath: /shared

    - name: reader
      image: wbitt/network-multitool:latest
      command: ["/bin/sh","-c"]
      args:
        - |
          echo "Reader started. Watching file...";
          tail -f /data/out.txt
      volumeMounts:
        - name: shared-data
          mountPath: /data
