apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shared
  namespace: storage-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-shared-hostpath
