apiVersion: v1
kind: Pod
metadata:
  name: reader-multitool
  namespace: storage-demo
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Multitool started. Press Ctrl+C to exit";
          sleep infinity
      volumeMounts:
        - name: shared
          mountPath: /data
          readOnly: true
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: pvc-shared
