apiVersion: v1
kind: Pod
metadata:
  name: reader-multitool
  namespace: storage-demo
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  containers:
    - name: multitool
      image: wbitt/network-multitool:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "multitool is ready"; 
          sleep infinity
      volumeMounts:
        - name: shared
          mountPath: /data
          readOnly: true
  volumes:
    - name: shared
      hostPath:
        path: /data/k8s-shared-demo
        type: DirectoryOrCreate
