apiVersion: v1
kind: Pod
metadata:
  name: reader-nginx
  namespace: storage-demo
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: pvc-shared
