apiVersion: v1
kind: Pod
metadata:
  name: writer
  namespace: storage-demo
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  containers:
    - name: writer
      image: busybox:1.36
      command: ["sh","-c"]
      args:
        - |
          mkdir -p /shared
          i=0
          while true; do
            i=$((i+1))
            echo "$(date -Iseconds) line=$i" | tee -a /shared/out.txt
            sleep 5
          done
      volumeMounts:
        - name: shared
          mountPath: /shared
  volumes:
    - name: shared
      hostPath:
        path: /data/k8s-shared-demo
        type: DirectoryOrCreate
