apiVersion: v1
kind: Pod
metadata:
  name: writer
  namespace: storage-demo
spec:
  containers:
    - name: writer
      image: busybox:1.36
      command: ["sh","-c"]
      args:
        - |
          i=0
          while true; do
            i=$((i+1))
            echo "$(date -Iseconds) line=$i" >> /shared/out.txt
            sleep 5
          done
      volumeMounts:
        - name: shared
          mountPath: /shared
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: pvc-shared
