apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange
  namespace: storage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange
  template:
    metadata:
      labels:
        app: data-exchange
    spec:
      containers:
        - name: writer
          image: busybox:1.36
          command: ["sh","-c"]
          args:
            - |
              mkdir -p /shared
              i=0
              while true; do
                i=$((i+1))
                echo "$(date -Iseconds) line=$i" | tee -a /shared/out.txt
                sleep 5
              done
          volumeMounts:
            - name: shared
              mountPath: /shared

        - name: reader
          image: wbitt/network-multitool:latest
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Reader started. Tail log...";
              tail -f /data/out.txt
          volumeMounts:
            - name: shared
              mountPath: /data
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: pvc-local-demo
